config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :tasks, only: [:create, :update, :destroy]

  get 'dashboard', to: 'todos#dashboard'
  get 'planilha', to: 'todos#planilha'

  root 'todos#index'

  resources :todos do
    collection do
      post 'upload_image', to: 'todos#upload_image'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :tasks, dependent: :destroy

  def num_tasks
    tasks.count
  end

  def progresso
    return 0 if tasks.count.zero? # evitar divisão por zero
    (tasks.where(done: true).count.to_f / tasks.count * 100).round(2)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:destroy]

  def create
    @task = Task.create(task_params)


    if @task.save
      redirect_to todo_path(@task.todo_id)
    else
      redirect_to root_path
    end

  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to todo_path(@task.todo_id)
    else
      redirect_to root_path
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to todo_path(@task.todo) }
      format.js
    end
  end

  private

    def task_params
      params.require(:task).permit(:title, :done, :todo_id)
    end


    def set_task
      @task = Task.find(params[:id])
    end

end

app/controllers/todos_controller.rb
require "google/cloud/vision/v1"

class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]


  # GET /todos or /todos.json
  def index
    @todos = Todo.all

    #filtro de busca
    @query = params[:query]

    if @query.present?
      @todos = @todos.where("name ILIKE ?", "%#{@query}%")
    end

  end

  def home
    @todos = Todo.includes(:tasks)
  end

  # GET /todos/1 or /todos/1.json
  def show
    @task = Task.new
    @tasks = @todo.tasks
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo}
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo}
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_path, status: :see_other}
      format.json { head :no_content }
    end
  end


  def dashboard
    @todos = Todo.includes(:tasks)

    @tasks_by_todo = @todos.each_with_object({}) do |todo, hash|
      hash[todo.id] = todo.num_tasks
    end

    @progress_by_todo = @todos.each_with_object({}) do |todo, hash|
      hash[todo.id] = todo.progresso
    end

    # convertendo os dados para um formato adequado para o JavaScript
    @todos_data = @todos.map do |todo|
      {
        id: todo.id,
        name: todo.name,
        num_tasks: todo.num_tasks,
        progress: todo.progresso
      }
    end.to_json

    Rails.logger.debug "Todos data: #{@todos_data.inspect}"
  end

  def planilha
    todos = Todo.all

    p = Axlsx::Package.new
    wb = p.workbook

    center_style = wb.styles.add_style(
      alignment: { vertical: :center, horizontal: :center, wrap_text: true }
    )
    edge_style = wb.styles.add_style(
      alignment: { vertical: :center, wrap_text: true }
    )
    percent_style = wb.styles.add_style(
      format_code: '0.00%',
      alignment: { vertical: :center, horizontal: :center, wrap_text: true }
    )

    wb.add_worksheet(name: "Relatório") do |sheet|
      sheet.add_row ["Lista", "Atividades", "Concluída?", "Percentual de Conclusão"],
                    style: [center_style, center_style, center_style, center_style]

      todos.each do |todo|
        tasks = todo.tasks
        next if tasks.empty?

        tasks.each do |task|
          sheet.add_row [
            todo.name,
            task.title,
            task.done ? 'Sim' : 'Não',
            todo.progresso / 100
          ], style: [center_style, edge_style, center_style, percent_style]
        end


        sheet.merge_cells("A#{sheet.rows.size - tasks.size + 1}:A#{sheet.rows.size}")
        sheet.merge_cells("D#{sheet.rows.size - tasks.size + 1}:D#{sheet.rows.size}")
      end
    end


    send_data p.to_stream.read, filename: 'ToDo.xlsx', type: "application/xlsx"
  end


  def upload_image
    if params[:image].present? && params[:image].content_type.start_with?("image/")
      image_path = params[:image].path

      image_annotator = Google::Cloud::Vision::V1::ImageAnnotator::Client.new

      response = image_annotator.document_text_detection image: image_path
      ocr_text = response.responses.first.full_text_annotation.text

      todo = Todo.create(name: 'Lista Fisica')

      ocr_text.each_line do |line|
        todo.tasks.create(title: line.strip) unless line.strip.empty?
      end

      redirect_to todo_path(todo)
    else
      redirect_to todos_path, alert: "Por favor, envie uma imagem."
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="logo-container">
    <p class="navbar-title"><%= link_to image_tag("logo.png", size: "80x20"), root_path %></p>
    <p class="navbar-title"><%= link_to "To Do List", root_path %></p>
  </div>
  <ul id="activities-links">
    <li><%= link_to "Listas", root_path, class: current_page?(root_path) ? 'active' : nil %></li>
    <li><%= link_to "Dashboards", dashboard_path, data: { turbo: "false" }, class: current_page?(dashboard_path) ? 'active' : nil %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/chart.js' %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'imagesfavicon.png' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, "Título" ,style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <% if action_name == "edit" %>
    <div>
      <%= form.submit "Atualizar"%>
    </div>
  <% else %>
    <div>
      <%= form.submit "Criar"%>
    </div>
  <% end %>

<% end %>

app/views/todos/_searchbar.html.erb
<%= stylesheet_link_tag "searchbar" %>

<%= form_tag root_path, method: :get do %>

    <label for="query">Nome da Lista:</label>
    <%= text_field_tag :query, params[:query], placeholder: "Opcional"%>

    <%= submit_tag "Buscar"%>
    <% if  @query.present? %>
        <%= link_to "Voltar", todos_path, id: "btn-back" %>
    <% end %>

<% end %>

app/views/todos/_todo.html.erb
<%= stylesheet_link_tag "todo" %>

<div id="<%= dom_id todo %>">
  <p>
    <strong>Título:</strong>
    <%= todo.name %>
  </p>

  <p>
    <strong>Progresso:</strong>
    <span class="progress-container">
      <span class="progress-bar" style="width: <%= todo.progresso  %>%;"></span>
      <span class="progress-label"><%= todo.progresso %>%</span>
    </span>
  </p>

</div>

app/views/todos/dashboard.html.erb
<%= stylesheet_link_tag "dashboard" %>

<div id="container">
    <div class="row">
        <div class="chart-container completion">
            <h3>Quantidade de Itens por Lista</h3>
            <canvas id="completionChart"></canvas>
        </div>

        <div class="chart-container radar">
            <h3>Progresso das Listas</h3>
            <canvas id="radarChart"></canvas>
        </div>
    </div>
</div>

<script>
let todos = <%= @todos_data.html_safe %>;

let completionChart = null;
let radarChart = null;

document.addEventListener('DOMContentLoaded', function() {
    updateCharts();
});

function generatePastelColors(numColors) {
    const colors = [];
    for (let i = 0; i < numColors; i++) {
        colors.push(generateRandomPastelColor());
    }
    return colors;
}

let h = 0;
function generateRandomPastelColor() {
    h += 133; 
    h = h % 360;
    return 'hsla(' + h + ', 100%, 50%, 0.4)';
}

function updateCharts() {
    if (completionChart !== null) {
        completionChart.destroy();
    }
    if (radarChart !== null) {
        radarChart.destroy();
    }

    const todoLabels = todos.map(todo => todo.name);
    const numTodos = todoLabels.length;
    const todoColors = generatePastelColors(numTodos);
    const taskData = todos.map(todo => todo.num_tasks);
    const progressData = todos.map(todo => todo.progress);

    // Criar o gráfico de barras (tasks por todo)
    const completionChartCtx = document.getElementById('completionChart').getContext('2d');
    completionChart = new Chart(completionChartCtx, {
        type: 'bar',
        data: {
            labels: todoLabels,
            datasets: [{
                label: 'Tarefas',
                data: taskData,
                backgroundColor: todoColors,
                borderWidth: 1,
                hoverOffset: 15
            }]
        },
        options: {
            scales: {
                x: {
                    ticks: {
                        font: {
                            size: 14
                        }
                    }
                },
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: 'Quantidade de Tarefas',
                        font: {
                            size: 16
                        }
                    }
                }
            },
            onClick: function(event, elements) {
                if (elements.length > 0) {
                    const index = elements[0].index;
                    const label = this.data.labels[index];
                    const baseUrl = window.location.origin;
                    window.location.href = `${baseUrl}/todos/${todos[index].id}`;
                }
            },
            onHover: function(event, elements) {
                event.native.target.style.cursor = elements.length > 0 ? 'pointer' : 'default';
            }
        }
    });

    // Criar o gráfico radar (progresso por todo)
    const radarData = {
        labels: todoLabels,
        datasets: [{
            label: 'Progresso (%)',
            data: progressData,
            backgroundColor: 'rgba(54, 162, 235, 0.2)',
            borderColor: 'rgba(54, 162, 235, 1)',
            borderWidth: 1
        }]
    };

    const radarChartCtx = document.getElementById('radarChart').getContext('2d');
    radarChart = new Chart(radarChartCtx, {
        type: 'radar',
        data: radarData,
        options: {
            scales: {
                r: {
                    suggestedMin: 0,
                    suggestedMax: 100,
                    pointLabels: {
                        font: {
                            size: 14
                        }
                    }
                }
            },
            onClick: function(event, elements) {
                if (elements.length > 0) {
                    const index = elements[0].index;
                    const label = this.data.labels[index];
                    const baseUrl = window.location.origin;
                    window.location.href = `${baseUrl}/todos/${todos[index].id}`;
                }
            },
            onHover: function(event, elements) {
                event.native.target.style.cursor = elements.length > 0 ? 'pointer' : 'default';
            }
        }
    });
}
</script>

app/views/todos/edit.html.erb
<%= stylesheet_link_tag "new" %>

<div class="new-todo-page">

  <h1>Editar Lista</h1>

  <div class="form-container">
    <%= render "form", todo: @todo %>
  </div>

  <br>

  <div class="back-link">
    <%= link_to "Ver Lista", @todo, class: "btn-back"  %> |
    <%= link_to "Voltar", todos_path, class: "btn-back" %>
  </div>

</div>

app/views/todos/index.html.erb
<%= stylesheet_link_tag "index" %>

<div class="todos-list">
  <h1>Olá! O que vamos fazer hoje?</h1>

  <%= render "searchbar" %>

  
  <div id="todos">
    <% @todos.each do |todo| %>
      <div class="todo-item">
        <%= render todo %>
        <p>
          <%= link_to "Visualizar a Lista", todo, class: "btn-show" %>
        </p>
      </div>
    <% end %>
  </div>

  <% if not @query.present? %>

    <div class="actions-buttons">
        <%= link_to "Nova Lista", new_todo_path, class: "btn-new" %>

        <% if @todos.any? %>
          <%= link_to "Gerar Planilha", planilha_path, class: "btn-planilha" %> 
        <% end %>

    </div>

    <div class="ocr-form">
      <%= form_with url: upload_image_todos_path, local: true, method: :post, multipart: true do |form| %>
      <%= form.label :image, "Envie sua lista física:" %>
      <%= form.file_field :image %>
      <%= form.submit "Enviar", class: "btn-submit-image" %>
      <%end%>
    
    </div>
    
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>


  <% end %>


</div>

app/views/todos/new.html.erb
<%= stylesheet_link_tag "new" %>
<div class="new-todo-page">
  <h1>Nova Lista</h1>

  <div class="form-container">
    <%= render "form" ,todo: @todo %>
  </div>

  <br>

</div>

app/views/todos/show.html.erb
<%= stylesheet_link_tag "show" %>
<div class="todo-list">
  <h2 class=todo-title><%= @todo.name %></h2>

  
<div class="tasks">
  <% @tasks.each do |task| %>
    <div class="task-item <%= 'done' if task.done %>">
      <div class="task-content">
        <% if task.done %>
          <strike>
            <p class="task-title"> <%= task.title %> </p>
          </strike>
        <% else %>
          <p class="task-title"> <%= task.title %> </p>
        <% end %>
      </div>
      
      <div class="task-actions">
        <%= form_with(model: task, remote: true, class: "task-checkbox-form") do |f| %>
          <%= f.check_box :done, checked: task.done, onchange: 'this.form.submit();', class: "task-checkbox" %>
        <% end %>
        <%= button_to 'x', task, method: :delete, class: "btn-delete-task" %>
      </div>
    </div>
  <% end %>
</div>

  
    <div class="new-task">
      <%= form_for @task, class: "new-task-form" do |f| %>
        <p><%= f.text_field :title, placeholder: "Adicionar nova tarefa", class: "task-input" %></p>
        <%= f.hidden_field :done, value: false %>
        <%= f.hidden_field :todo_id, value: @todo.id %>
        
        <div class="buttons">
          <%= f.submit "Adicionar tarefa", class: "btn-submit" %>
        </div>
      <% end %>
    </div>

    <div class="todo-actions">

      <div class="action-buttons">

        <%= link_to "Voltar", todos_path, class: "btn-back" %>
        <%= link_to "Editar Nome da Lista", edit_todo_path(@todo), class: "btn-edit" %> 
        <%= button_to "Deletar Lista", @todo, method: :delete, class: "btn-delete" %>
      
      </div>
    </div>
    
  </div>
</div>